<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
	</PropertyGroup>
    <ItemGroup>
      <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.142" />
    </ItemGroup>
	
	<ItemGroup>

		<Compile Update="HoldClip - Copy.cs">
		  <DependentUpon>HoldClip.xaml</DependentUpon>
		</Compile>

		<Compile Update="TsTimeline.cs">
			<DependentUpon>TsTimeline.xaml</DependentUpon>
		</Compile>
		<Compile Update="ClipBase.cs">
			<DependentUpon>ClipBase.xaml</DependentUpon>
		</Compile>
		<Compile Update="ClipsControl.cs">
			<DependentUpon>ClipsControl.xaml</DependentUpon>
		</Compile>

		<Compile Update="TriggerClip.cs">
			<DependentUpon>TriggerClip.xaml</DependentUpon>
		</Compile>

		<Compile Update="HoldClip.cs">
			<DependentUpon>HoldClip.xaml</DependentUpon>
		</Compile>
		<Compile Update="Timeline.cs">
			<DependentUpon>Timeline.xaml</DependentUpon>
		</Compile>
	</ItemGroup>
</Project>
